version: '3'
services:
  front_invest:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/home/node/front-invest:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true